apiVersion: v1
kind: Service
metadata:
  name: frontend-lb
  annotations:
    # Note that the backend talks over HTTP.
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  type: LoadBalancer
  loadBalancerIP:
  ports:
  - port: 80
    name: http
    # Use named container port.
    targetPort: web
  selector:
    run: frontend