---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: newsfeed
spec:
  selector:
    matchLabels:
      run: newsfeed
  replicas: 1
  template:
    metadata:
      labels:
        run: newsfeed
    spec:
      containers:
      - name: newsfeed
        image: 722910786382.dkr.ecr.us-east-1.amazonaws.com/newsfeed:latest
        ports:
          - name: web2
            containerPort: 8080
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080