---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      run: frontend
  replicas: 2
  template:
    metadata:
      labels:
        run: frontend
    spec:
      containers:
      - name: frontend
        image: 722910786382.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
        ports:
          - name: web
            containerPort: 8070
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /ping
            port: 8070
        readinessProbe:
          httpGet:
            path: /ping
            port: 8070
    